---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    myapplabelname: queue

  ports:
    - name: http
      port: 8161
      nodePort: 30010
    - name: endpoint
      port: 61616

  type: NodePort

---
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    myapplabelname: tracker

  ports:
    - name: http
      port: 8080
      nodePort: 30020

  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    myapplabelname: api-gateway

  ports:
    - name: http
      port: 8080
      nodePort: 30030

  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: webapp

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    myapplabelname: webapp

  ports:
    - name: http
      port: 80
      nodePort: 30080

  type: NodePort
